language: c

sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - VERSION_TO_COVER=6.6
  matrix:
    - RACKET_VERSION=6.0   PACKAGE=struct-updaters
    - RACKET_VERSION=6.2   PACKAGE=struct-updaters
    - RACKET_VERSION=6.4   PACKAGE=struct-updaters
    - RACKET_VERSION=6.6   PACKAGE=struct-updaters
    - RACKET_VERSION=HEAD  PACKAGE=struct-updaters
    - RACKET_VERSION=6.3   PACKAGE=alexis-util
    - RACKET_VERSION=6.4   PACKAGE=alexis-util
    - RACKET_VERSION=6.6   PACKAGE=alexis-util
    - RACKET_VERSION=HEAD  PACKAGE=alexis-util
    - RACKET_VERSION=6.2   PACKAGE=alexis-multicast
    - RACKET_VERSION=6.4   PACKAGE=alexis-multicast
    - RACKET_VERSION=6.6   PACKAGE=alexis-multicast
    - RACKET_VERSION=HEAD  PACKAGE=alexis-multicast

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - if [ "${VERSION_TO_COVER}" == "${RACKET_VERSION}" ]; then raco pkg install --deps search-auto cover cover-coveralls; fi

install:
  - raco pkg install --deps search-auto --link $TRAVIS_BUILD_DIR/$PACKAGE

before_script:

script:
  - raco test -xp $PACKAGE
  - if [ "${VERSION_TO_COVER}" == "${RACKET_VERSION}" ]; then raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage -p $PACKAGE; fi

after_script:
